# Site configuration
#domain: "http://songroger.win"
baseurl:  # the subpath of your site, e.g. /blog/
#url: http://jiangqh.info # the base hostname & protocol for your site
permalink: /:title/
date_format: "ordinal"
avatar: /images/icon.jpg
about: /images/icon.jpg
favicon: /images/icon.jpg
basecss: 
# Theme specific configuration
title: Jiang's Home
description: >
  Hi there, welcome to my blog. My name is Jiang Qinhong

# Contact and social media links
#twitter_username: songrogero
#github_username: songroger
#facebook_username: song.roger.1
#instagram_username: songroger198
#linkedin_username: songroger

#exclude: ['node_modules', 'gulpfile.js', 'package.json']
markdown: kramdown
kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account of "/_layouts/post.html"
# before deploy your webpage
enable_comment: false
duoshuo_short_name: jiangqh

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num
